### ISSUE TITLE
update to React 16

### ISSUE THREAD

**Issue by paulcollett** [paulcollett/react-masonry-css#10]
As suggested by @balazsorban44 https://github.com/paulcollett/react-masonry-css/pull/9#issuecomment-340579907 which includes a link to changes in React 16 https://reactjs.org/blog/2017/09/26/react-v16.0.html#packaging

Ideally this component would support both 15 and 16 at the same time if possible. If not, we'll look into a new major release which should document new support and instruct how to install the older react 15 version of this package

**Comment by balazsorban44** [comment]
Everybody is encouraged to update to 16, there are not many disadvantages really. The only breaking change is PropTypes, which can be easily fixed using the [prop-types](https://www.npmjs.com/package/prop-types) npm package.

**Comment by paulcollett** [comment]
Sounds good @balazsorban44. Thanks for the info, this will be an easy addition if thats the only thing needed for react 16

**Comment by balazsorban44** [comment]
I am working on it, just a little bit busy with school right now. Will push the code when I am finished/have time.

**Comment by paulcollett** [comment]
Has been working with React 16 for some time
