### ISSUE TITLE
Is this compatible with virtualization?

### ISSUE THREAD

**Issue by PabloMessina** [paulcollett/react-masonry-css#12]
The demo looks incredibly smooth, but I'm wondering whether this is compatible with virtualization, i.e., just rendering the elements that are currently visible in the viewport, like react-virtualized Masonry (https://github.com/bvaughn/react-virtualized/blob/master/docs/Masonry.md). It would be great to have a react-masonry which is both this smoothly responsive and virtualized.

**Comment by paulcollett** [comment]
Hi @PabloMessina, to achieve this we'd be needing to render all the elements to get the heights before building the layout. In the interest of keeping this component fast on render changes with a small filesize we do not provide a lot of "extra" functionality like this and have been trying to avoid features that require this duel rendering
