### ISSUE TITLE
Peer dependency on React 15

### ISSUE THREAD

**Issue by lorvsso** [paulcollett/react-masonry-css#16]
React 16 users will be getting this warning in the console.

```
react-masonry-css@1.0.10" has incorrect peer dependency "react@^15.0.0".
```

Is there any reason that `react-masonry-css` needs React 15, or could this be updated now that React is at v16.3.2?

**Comment by paulcollett** [comment]
Thanks for bringing it to my attention jack, no reason for us not to bump
to 16. I'll update that when I can unless you'd like to which would be most
appreciated!
