### ISSUE TITLE
Add Type Definitions

### ISSUE THREAD

**Issue by tdharmon** [paulcollett/react-masonry-css#24]
I'm using Typescript and wanted to use this repo and have it typed correctly. For future typescript users who want to use this package, it would be really helpful to add a `.d.ts` file. I created my own declarations file that looks like this:

```javascript
declare module 'react-masonry-css' {
  import * as React from 'react';

  export interface MasonryProps {
    breakpointCols?: Object;
    columnClassName?: string;
  }

  export default class Masonry extends React.Component<MasonryProps & React.HTMLProps<HTMLElement>, any> {
    render(): JSX.Element;
  }
}
```

This could be a start to that file (it was mostly generated for me by [react-to-typescript](https://www.npmjs.com/package/react-to-typescript-definitions), with some minor massaging). My understanding is that Typescript can't look at PropTypes but needs typings explicitly in a `.d.ts` file.

**Comment by paulcollett** [comment]
Ah this is interesting @tdharmon. I myself would need to scrub up on typescript to roll this out reliably. Until then PRs for something like this, from anyone would be very welcomed
