### ISSUE TITLE
Add "originLeft" option

### ISSUE THREAD

**Issue by adamsoffer** [paulcollett/react-masonry-css#26]
Masonry has an option for controlling the horizontal flow of the layout. By default, item elements start positioning at the left, with `originLeft: true`. If you want them to start positioning at the right you simply set it to `false`. How does one achieve the same thing with this library?

Loving this library. Thank you!

**Comment by paulcollett** [comment]
Hi @adamsoffer, currently not supported though could be a trivial addition. Just so I understand it better, could you give me a bit of background on your and other common use cases for this feature?

**Comment by adamsoffer** [comment]
Sure! Here's the page where I'm using the library: https://thinkfwd.co/about

On the bottom of the page, notice how the three team members are stacked? The third one "floats" right. I was able to achieve that in a sort of hacky fashion - I created a hidden third element so that that the library forces the forth one to the right. Ideally, the library would provide an option for me to set the items origin to the right.

Hope that makes sense.
