### ISSUE TITLE
Enabling filtering

### ISSUE THREAD

**Issue by hugolanuit** [paulcollett/react-masonry-css#30]
Hey Paul. 

First off all great job on this component. It's allowing me to achieve a layout grid I couldn't do with masonry.

I need to be able to filter elements within the grid. Right now when I do, it removes them from the column they are in without reshuffling the whole grid (redistributing the elements accordingly). How would one achieve this? Is there a way to do a transition as well? 

Thanks.

**Comment by paulcollett** [comment]
Hi @hugolanuit, some time has passed since you posted this issue. Did you manage to find a solution?

If not, I'm curious to the implementation. Specifically how you're removing an item from the array? Any info would be great, so we can extend the plugin to support this way of deleting items
