### ISSUE TITLE
Centering items?

### ISSUE THREAD

**Issue by erosenberg** [paulcollett/react-masonry-css#31]
I want to be able to center the columns or at least change their `justify-content` value easily.
Is there a way to do this?

**Comment by paulcollett** [comment]
You can wrap your Masonry component with some divs that apply the centered layout to your needs. Maybe something like the following (translated into JSX of course)..

```html
<div style="width: 100%;display:flex;justify-content:center">
  <div style="width:50%">
    <Masonry .... />
  </div>
</div>

```
