### ISSUE TITLE
IE 10 props/_this undefined

### ISSUE THREAD

**Issue by kennypascal** [paulcollett/react-masonry-css#32]
Great work with this component!

I am using this with Preact & Preact Compat. When running in IE 10 I get an error message saying:

Unable to get property 'breakpointCols' of undefined or null reference. 

![screen shot 2019-02-21 at 4 45 28 pm](https://user-images.githubusercontent.com/2301576/53204313-4c9d0b00-35f9-11e9-80b8-40a5d0808f05.png)

It appears the props are not defined  in '_this' via the _possibleConstructorReturn function. Any ideas?

See attached: The props object has a value _this does not have props.
![screen shot 2019-02-21 at 4 51 54 pm](https://user-images.githubusercontent.com/2301576/53204354-5fafdb00-35f9-11e9-9cf1-e2f9cf56177b.png)

Note: This does not occur using IE Edge

**Comment by paulcollett** [comment]
I've personally moved away from testing <=ie11 support so it unfortunately this issue wont be one I can help out with
