### ISSUE TITLE
Add feature to make all tiles on the last row line up at the bottom.

### ISSUE THREAD

**Issue by romiem** [paulcollett/react-masonry-css#38]
Is this possible using this library? I've attached a diagram showing what I mean.

![Frame 1](https://user-images.githubusercontent.com/639983/66576237-41d6bc80-eb6f-11e9-9fec-861ad91f1e97.png)

**Comment by paulcollett** [comment]
It should be possible, though outside of what we'd consider stable or for
documentation.

So, under the hood this plugin wraps a div around each column. You could
add various flex CSS rules to both the container and your columns and then
 flex-grow: 1 the last child.

Does that give you enough info to point you in the right direction?
