### ISSUE TITLE
Suggestion: prop on children to let them span the entire row

### ISSUE THREAD

**Issue by ardeaf** [paulcollett/react-masonry-css#40]
Let's say your masonry is 3 columns wide, but you'd like to highlight one of them items in the list of children. It'd be cool to allow that one item to span the entire row via a prop.

**Comment by paulcollett** [comment]
Nice idea, and actually something you may be able to achieve currently with more control than we could work into the plugin. 

So to do this you can do is render your full width item with 2 Masonry components, one above with the precdeding items and one below with the items that follow. When you no longer need your full width item you can return to the 1 Mansonry layout.

Im curious to see if this could work

**Comment by ardeaf** [comment]
I haven't had the chance to test this yet, but the workaround should work.
