### ISSUE TITLE
adding ref to wrapper element

### ISSUE THREAD

**Issue by violabg** [paulcollett/react-masonry-css#41]
I wanted to use react-infinite-scroll-hook with react-masonry-css, in order to do so I needed to pass the ref ( by useRef hook) to the actual list wrapper div.

because adding it to the Masonry component did not work:

```jsx
const infiniteRef = useInfiniteScroll({
    loading: isLoading,
    // This value is set to "true" for this demo only. You will need to
    // get this value from the API when you request your items.
    hasNextPage,
    onLoadMore: onPaginatedSearch,
    scrollContainer: "window"
  });

<Masonry
        ref={infiniteRef}
        breakpointCols={breakpointColumnsObj}
        className="masonry"
        columnClassName="masonry-column"
      >...</Masonry>
```

so I have forked you repo and change the code to support this:

```js
render() {
    const {
      breakpointCols,
      columnClassName,
      column,
      elRef,
      ...wrapperProps
    } = this.props;

    return (
      <div ref={elRef} {...wrapperProps}>
        {this.renderColumns()}
      </div>
    );
  }
```

so tha I could do this:
```jsx
const infiniteRef = useInfiniteScroll({
    loading: isLoading,
    // This value is set to "true" for this demo only. You will need to
    // get this value from the API when you request your items.
    hasNextPage,
    onLoadMore: onPaginatedSearch,
    scrollContainer: "window"
  });

<Masonry
        elRef={infiniteRef}
        breakpointCols={breakpointColumnsObj}
        className="masonry"
        columnClassName="masonry-column"
      >...</Masonry>
```

I this could be potentially useful for other use cases, so it would be nice if you could include it in your code.

**Comment by paulcollett** [comment]
I'm not familiar with the useinfinatescroll hook though I'd assume you could also achieve what your after by wrapping the Masonry component in an extra div, which that div you can reference the normal way. This will help keep the Masonry component  nicely encapsulated

**Comment by violabg** [comment]
you are right adding the ref to the parent div worked.
thanks
