### ISSUE TITLE
Warning: Failed prop type: Invalid prop `breakpointCols` of type `number` supplied to `Masonry`, expected `object`.

### ISSUE THREAD

**Issue by dandv** [paulcollett/react-masonry-css#45]
Just started using the library with Gatsby, pasted the example from the README, and I'm seeing this warning in the console. The layout works fine.

![image](https://user-images.githubusercontent.com/33569/67302919-3f515c80-f4b7-11e9-9f2c-f30f163e8d97.png)

**Comment by paulcollett** [comment]
Thanks Dan. Typical usage would be passing an object with breakpoint and
column could t but a number to indicate a set amount of columns is also
valid, and shouldn't error. I'll get this updated.

**Comment by paulcollett** [comment]
Has been fixed in:
https://github.com/paulcollett/react-masonry-css/commit/724ad866805226d8ead5def41b92ba9abc46c2be

In this I've tightened up the documentation, handling of all props and laying down an interface for future features.
