### ISSUE TITLE
Is this type of Masonry possible asking for a feature

### ISSUE THREAD

**Issue by faizhameed** [paulcollett/react-masonry-css#46]
I have a particular type of requirement where tiles are added dynamically, each tiles will be having different height and width
I wanted it to look it like this
![masonry](https://user-images.githubusercontent.com/41015883/71901116-37838900-3185-11ea-8451-2f116a630889.png)

If this is possible I wanted to try this library

**Comment by paulcollett** [comment]
This Masonry component only supports equal width columns with each item spanning just one column. 

Unfortunately this could be restrictive for what you're after. We keep this plugin to just supporting this popular use-case for optimization reasons

**Comment by faizhameed** [comment]
OK thanks, i tried several plugins finally found this one by which i was able to replicate my use case
https://github.com/STRML/react-grid-layout
thanks
