### ISSUE TITLE
cards overlap when total # of cards = # of default columns - 1

### ISSUE THREAD

**Issue by larabjork** [paulcollett/react-masonry-css#52]
I'm running into a bug where cards overlap under a specific condition: when the total # of cards is equal to whatever I'm using as a default # of columns minus one. So, with the breakpoints set as follows, I'm getting overlapping cards (see image) when there are only 2, but as soon as I add a 3rd card, it's fine, and continues to be fine as more cards are added. Is this a Masonry issue or something else?

const breakpointColsGoals = {
  default: 3,
  1370: 2,
  740: 1,
};

![image](https://user-images.githubusercontent.com/54046331/79614694-eead6b80-80b5-11ea-8eec-1b92944aaceb.png)

**Comment by paulcollett** [comment]
This may be because you content has a fixed width, rather than letting the columns dictate the size. There may be some additional help here: https://github.com/paulcollett/react-masonry-css/issues/22
