### ISSUE TITLE
colSpan?

### ISSUE THREAD

**Issue by thealjey** [paulcollett/react-masonry-css#54]
I would like to have a two column masonry container with some items in it spanning both columns.
Is that possible?

**Comment by paulcollett** [comment]
There is a workaround, please have a look at https://github.com/paulcollett/react-masonry-css/issues/40 - hope that helps!

**Comment by thealjey** [comment]
yeah, that's what I ended up doing, unfortunately
a bit awkward code, but it works, sorta
they really need to add something like "display: masonry" into the css spec
because every approach that we have to masonry layouts currently has its own list of drawbacks
