### ISSUE TITLE
IE 11 - unequal width of the columns initially

### ISSUE THREAD

**Issue by solankirohan** [paulcollett/react-masonry-css#55]
Hello - I am observing that on IE 11 when the masonry layout renders, it initially renders with unequal column widths, then if I perform any interactions in the page like clicks, the columns are I guess re-renders and they are displayed with correct width (equal width column).  In Chrome, this works without any issues.
Has anyone observed this issue? 
I have a release planned on Monday, hence looking for some urgent help, at least if there are any workarounds. thank you in advance.

**Comment by paulcollett** [comment]
Things you can try:
1. make sure your flex values have been automatically or manually "vendor prefixed" with ie11 support
2. ie11 specific hacks for additional css rules (play with setting specific width on child items etc)

It's also worth noting that IE11 also has very low market share these days. So the extra effort may not be worth it in a lot of cases, but I can't speak for yours specifically

**Comment by solankirohan** [comment]
Thanks a lot, @paulcollett for responding so fast. Unfortunately, this is an enterprise app, hence I need to support IE as well :( . I'll take a look at your suggestions.
