### ISSUE TITLE
elements with column span

### ISSUE THREAD

**Issue by vog3nim** [paulcollett/react-masonry-css#62]
Hi, I want to create a Dashboard that displays many elements with variable dimensions in a masonry grid. This Component works fine for me, even with the dynamic heights, but I need to stretch some of the elements over 2 columns. Implementing this with css leads to an overlap with the elements around it. 
Is there any possibility to set some elements wider, without destructing the whole layout or, if not, is this a planned feature for the future?

Thanks in advance

**Comment by paulcollett** [comment]
Currently this library only works with items that are fixed width. This is a common enough use case that this plugin Is specifically optimized for, both performance and filesize. 

Saying that, there is plenty of great bi-directional masonary libraries out there. Hopefully you’ve found something that works for you!
