### ISSUE TITLE
Can this be done completely with CSS alone, in 2020 browsers?

### ISSUE THREAD

**Issue by dandv** [paulcollett/react-masonry-css#63]
In case this package isn't maintained, I was wondering if the layout can be achieved with CSS alone. Some attempts I haven't fully looked into:

- https://css-tricks.com/adaptive-photo-layout-with-flexbox/
- https://dev.to/j3nnning/masonry-with-css-grid-1e59
- https://w3bits.com/css-grid-masonry/

**Comment by paulcollett** [comment]
I revisited this earlier in the year and my takeaway was that pure CSS still isn’t possible even with the latest css spec features.

I’ve seen some attempts that manage it with images only, but the setup doesn’t lend itself to an easy to use package.

Im totally open to any findings to improve our layout strategy
