### ISSUE TITLE
Any way to center childrens?

### ISSUE THREAD

**Issue by Hisashin7331** [paulcollett/react-masonry-css#69]
I tried using justify-content: space-around and center, doesn't work. Is there any prop that can center my divs?

**Comment by BanJoeH** [comment]
this worked for me :
`.conainer {
  width: 100%;

  .my-masonry-grid {
    display: flex;
    margin-left: -20px;
    width: 100%;

    .my-masonry-grid_column {
      display: flex;
      flex-direction: column;
      align-items: center;
      padding-left: 30px;
      background-clip: padding-box;
    }
  }
}`

**Comment by paulcollett** [comment]
Correct, column alignment or children in the columns can be achieved with CSS flexbox rules
