### ISSUE TITLE
Failed to compile (You may need an appropriate loader to handle this file type.)

### ISSUE THREAD

**Issue by balazsorban44** [paulcollett/react-masonry-css#7]
Hi, I wanted to give this a try, but unfortunately I get the following error:
```
./node_modules/react-masonry-css/src/react-masonry-css.js
Module parse failed: /home/user/github/project/node_modules/react-masonry-css/src/react-masonry-css.js Unexpected token (92:13)
You may need an appropriate loader to handle this file type.
| 
|     return childrenInColumns.map((items, i) => {
|       return <div
|         key={i}
|         className={columnClassName}
```

I am on React 16, using  `create-react-app` .

**Comment by paulcollett** [comment]
Thanks for reaching out @balazsorban44, I'll take a quick look. Are you using webpack? If so, you may need the `babel-loader` to transform this from es6 to es5 javascript.

**Comment by paulcollett** [comment]
Ok, I'm seeing it too.

![image](https://user-images.githubusercontent.com/1904774/32082050-cf5cb094-ba6d-11e7-8e3b-f0fa2ff4319a.png)

This is occurring because `babel-loader` is needing the `babel-preset-react` in your setup. Ideally, you shouldn't have to worry about this for external packages like this one.. so I'll see if theres something I can do!

**Comment by paulcollett** [comment]
updated now and should work as expected without needing to do anything special. Let me know how you go!

As a side note, if you run into that error again on any of your own JSX, you may need that `babel-preset-react` as a part of your babel/webpack compiling step.

**Comment by balazsorban44** [comment]
That issue is solved, I can confirm it. But now I get another one. For some reason, no matter what I set the breakpointCols to, it only displays one left aligned column.

**Comment by balazsorban44** [comment]
UPDATE: It was a local problem. Thank you for the quick solution.
