### ISSUE TITLE
[Masonry] The property "columnClassName" requires a string - Error shows in Chrome console

### ISSUE THREAD

**Issue by harikrishnanp** [paulcollett/react-masonry-css#70]
I'm using **react-masonry-css** module. Recently I'm getting the below error in my Chrome Console. Any common reason for this error?

`[Masonry] The property "columnClassName" requires a string                myJSFile:formatted:3200`

When I went to the JS file line number which shows error, I got the below code.

` key: "logDeprecated",
                value: function(t) {
                    console.error("[Masonry]", t)
                }`
                
  Please advice.

**Comment by amillward** [comment]
Adding `<Masonry columnClassName="".../>` solved this for me. But ideally this shouldn't be required

**Comment by harikrishnanp** [comment]
@amillward The same worked for me as well. After adding the above prop the error message has disappeared.
