### ISSUE TITLE
Publish react 17 peer dependency fix to npm

### ISSUE THREAD

**Issue by in43sh** [paulcollett/react-masonry-css#71]
I'm trying to install this package for my React project. I have React version 17.0.1. Here is the error that my console gives to me when I try to install it:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: front-end-nextjs@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-masonry-css@1.0.14
npm ERR! node_modules/react-masonry-css
npm ERR!   react-masonry-css@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/serg/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/serg/.npm/_logs/2021-02-25T07_56_40_785Z-debug.log

**Comment by damland** [comment]
I confirm that I have the same problem, a fix is needed...

**Comment by dogukanolgun** [comment]
Yes

**Comment by AlFalahTaieb** [comment]
Same

**Comment by hareesh43** [comment]
same problem here.

**Comment by paulcollett** [comment]
Fixed in https://github.com/paulcollett/react-masonry-css/commit/648e4ea739f1f7b5d59fa066d574246a498d4e40
