### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by balazsorban44** [paulcollett/react-masonry-css#8]
![image](https://user-images.githubusercontent.com/18369201/32084062-4cc0d854-bac7-11e7-8d2d-e82495c17ce8.png)

Sorry, but I have a new issue when I am trying to run `yarn build`
I am provided the following link:
[http://bit.ly/2tRViJ9](http://bit.ly/2tRViJ9)

**Comment by paulcollett** [comment]
I've just removed the es6 version from the package. Lets see if that works now

**Comment by balazsorban44** [comment]
![image](https://user-images.githubusercontent.com/18369201/32094388-e432d6dc-baff-11e7-8f7a-bef2b0eb5399.png)
I still get the error.

**Comment by balazsorban44** [comment]
It is now building without a problem. :+1:
