### ISSUE TITLE
🛑⚠️ Abandoned Project ⚠️ ?

### ISSUE THREAD

**Issue by ADTC** [paulcollett/react-masonry-css#97]
Last release was in Apr 2021.

**Comment by paulcollett** [comment]
closed as non-constructive

**Comment by ADTC** [comment]
@paulcollett the reason why I asked is because there didn't seem to be any new commits or any activity including responding to issues.

It's weird you have chosen to respond to this one by closing it but didn't give any constructive feedback about the future of the project. We're still left wondering whether this project will be resumed for maintenance or left abandoned. 😂
